server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_management
    username: root
    password: Dilshara224#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
    com:
      example: DEBUG
